apiVersion: weblogic.oracle/v1
kind: Cluster
metadata:
  labels:
    weblogic.domainUID: sample-domain1
  name: sample-domain1-cluster-1
  namespace: sample-domain1-ns
spec:
  clusterName: cluster-1
  replicas: 1
  