apiVersion: weblogic.oracle/v9
kind: Domain
metadata:
  labels:
    weblogic.domainUID: sample-domain1
  name: sample-domain1
  namespace: sample-domain1-ns
spec:
  adminServer:
    adminChannelPortForwardingEnabled: true
  clusters:
  - name: sample-domain1-cluster-1
  configuration:
    introspectorJobActiveDeadlineSeconds: 1500
    model:
      auxiliaryImages:
      - image: phx.ocir.io/weblogick8s/quick-start-aux-image:v1
      domainType: WLS
      runtimeEncryptionSecret: sample-domain1-runtime-encryption-secret
    overrideDistributionStrategy: Dynamic
  domainHome: /u01/domains/sample-domain1
  # domainHomeSourceType: FromModel
  # domainHomeSourceType: PersistentVolume
  # managedServers:
  #   - serverName: test-server
  failureRetryIntervalSeconds: 120
  failureRetryLimitMinutes: 1440
  httpAccessLogInLogHome: true
  image: container-registry.oracle.com/middleware/weblogic:14.1.1.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: weblogic-repo-credentials
  includeServerOutInPodLog: true
  introspectVersion: "1"
  logHome: /u01/domains/logs
  maxClusterConcurrentShutdown: 1
  maxClusterConcurrentStartup: 0
  maxClusterUnavailable: 1
  replaceVariablesInJavaOptions: false
  replicas: 1
  restartVersion: "1"
  serverPod:
    env:
    - name: JAVA_OPTIONS
      value: -Dweblogic.StdoutDebugEnabled=true
    - name: USER_MEM_ARGS
      value: '-Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx512m '
    - name: RESTART_MAX
      value: "1"
    - name: RESTART_INTERVAL
      value: "7200"
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      timeoutSeconds: 10
    resources:
      requests:
        cpu: 550m
        memory: 768Mi
    volumeMounts:
    - mountPath: /u01/domains
      name: weblogic-domain-storage-volume
      subPath: domains
    volumes:
    - name: weblogic-domain-storage-volume
      persistentVolumeClaim:
        claimName: sample-domain1-weblogic-sample-pvc
  # serverStartPolicy: AdminOnly
  webLogicCredentialsSecret:
    name: sample-domain1-weblogic-credentials