apiVersion: weblogic.oracle/v9
kind: Domain
metadata:
  labels:
    weblogic.domainUID: sample-domain1
  name: sample-domain1
  namespace: sample-domain1-ns
spec:
  clusters:
  - name: sample-domain1-cluster-1
  configuration:
    model:
      auxiliaryImages:
      - image: phx.ocir.io/weblogick8s/quick-start-aux-image:v1
      domainType: WLS
      runtimeEncryptionSecret: sample-domain1-runtime-encryption-secret
    initializeDomainOnPVL: true
    overrideDistributionStrategy: Dynamic
    introspectorJobActiveDeadlineSeconds: 1500
  domainHome: /u01/domains/sample-domain1
  domainHomeSourceType: FromModel
  failureRetryIntervalSeconds: 120
  failureRetryLimitMinutes: 1440
  httpAccessLogInLogHome: true
  image: container-registry.oracle.com/middleware/weblogic:14.1.1.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: weblogic-repo-credentials
  includeServerOutInPodLog: true
  introspectVersion: "1"
  logHome: /u01/domains/logs
  maxClusterConcurrentShutdown: 1
  maxClusterConcurrentStartup: 1
  maxClusterUnavailable: 1
  replaceVariablesInJavaOptions: false
  replicas: 1
  restartVersion: "1"
  serverPod:
    env:
    - name: JAVA_OPTIONS
      value: -Dweblogic.StdoutDebugEnabled=true
    - name: USER_MEM_ARGS
      value: '-Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx512m '
    resources:
      requests:
        cpu: 850m
        memory: 768Mi
    volumeMounts:
    - mountPath: /u01/domains
      subPath: domains
      name: weblogic-domain-storage-volume
    volumes:
    - name: weblogic-domain-storage-volume
      persistentVolumeClaim:
        claimName: sample-domain1-weblogic-sample-pvc
  serverStartPolicy: IfNeeded
  webLogicCredentialsSecret:
    name: sample-domain1-weblogic-credentials